spring.application.name=iam-service

spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres.ypqqnvcecuurnsdiiabn}
spring.datasource.password=${DB_PASSWORD:Kreg@60001756}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.port=8080

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200,http://localhost:8080,http://localhost:8081}

security.jwt.secret=replace_with_minimum_32_chars_secret_key_for_hs256
security.jwt.expiration-minutes=120

topics.iam-user-registered=iam.user.registered
topics.iam-user-logged-in=iam.user.logged-in
topics.iam-role-assigned=iam.role.assigned
